name: Backend CICD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t christopherpallo2000/cp-delete-client-service .
      - name: Publish image to docker hub
        run: docker push christopherpallo2000/cp-delete-client-service:latest   

  deploy: 
    needs: build
    runs-on: client-delete    
    steps:
      - name: Pull image from docker hub
        run: docker pull christopherpallo2000/cp-delete-client-service:latest
      - name: delete Old Container
        run: docker rm -f deleteclientService || true
      - name: Run docker container
        run: docker run -d --name deleteclientService -p 8097:8097 christopherpallo2000/cp-delete-client-service